# Generated by Django 2.2.2 on 2020-04-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=40)),
                ('lName', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
